### ISSUE TITLE
Plans for federation / roadmap?

### ISSUE THREAD

**Issue by WillemMali** [Minds/engine#11]
I was just wondering if there are any plans for implementing federation for Minds, I couldn't find a roadmap so perhaps it'd be a good idea to start writing one, it could include an "off-road"-section to explain why certain popular or obvious suggestions aren't implemented.

Some suggestions for the roadmap (by me, I hereby assign the copyright to Minds Inc. and license it MIT):

* [ ] Federation
    * [ ] Implement federation
    * [ ] Add documentation on federation
        * [ ] In generated docs
        * [ ] Quick mention on `/README.md`
* [ ] What is Minds Inc. / why should a redpilled programmer trust you and want to contribute?
    * [ ] Add to docs, `/README.md`, about page
* [ ] State standpoint on outside contributions, if looking for contributors:
    * [ ] Add contribution guide
    * [ ] Add "good beginner issues" label
* [ ] Copyright footers on docs are out of date

Perhaps my roadmap is a bit too fine-grained right now, and would be better as a bunch of issues in the issue tracker; however I'm not super invested in this platform as of right now and I don't want to spam the issue tracker so I refrained from that.

**Comment by markharding** [comment]
Thanks for this. To be brutally honest, my view is that the current examples of 'federation' have failed from both a consumer and technical point of view. The interfaces and experiences are too confusing for over 99% of users and whilst they claim to be decentralized, when you look into them deeper, they are not at all. 

I believe the solution would be to create a torrent style, p2p network with no central points. This would require a huge shift in the way we use browsers and social networks. Projects like Webtorrent and WebRTC are making this more and more possible

**Comment by ottman** [comment]
I tend to agree with Mark. However I'm not going to say we'd be unwilling to accept an intelligent implementation/contribution of current federation status quo. It depends. But for us it makes more sense to putting our resources to truly P2P. We want this for reasons from privacy to scalability and web freedom.

**Comment by WillemMali** [comment]
I also believe a P2P-style network would be ideal, perhaps in combination
with "gateway nodes" for users that only access the network via the
browser, providing identities for "leech" users under their
banner/namespace.

Some combination of ratings, web-of-trust, and meta-ratings (rating graph
isomorphism? A recommendation system based on rating agreement, to
automatically separate bots from humans?) would be necessary to combat
spam/abuse in a semi-automated fashion, and the process would have to be
transparant to detect abuse of the system.

Sorry that my post is a bit rambly, I've been having a hard time putting
these ideas together in a structured way, I've been trying for at least a
year.

**Comment by markharding** [comment]
I'm closing this issue as its been a while with no activity. Feel free to continue the conversation over in the Open Source Group (https://www.minds.com/groups/profile/365903183068794880).
